(define (problem problema)
    (:domain tareas-ext2)
    (:objects 
        reason_streetmaps distribute_museums produce_antitrustlaw improvise_cancer instruct_arnoldfred incorporate_moon compile_drugdictionary customize_localgovt propose_supremecourt preside_travelinfo share_investing analyze_aviation collaborate_tvguide dedicate_localgovt commence_travelinfo present_antiquestock win_gods refer_politics inform_smokingsettlement experiment_libraries boost_geography centralize_usstatesites enter_stockexchanges trace_stockcertificates rectify_stocksbonds compare_greekgods extrapolate_people enlarge_dinosaurs attract_pregnancy nurse_stockexchanges foster_nosmoking spoke_smokingsettlement conduct_corporatenews start_geometry enhance_geography govern_drugeducation transfer_spaceshuttle visualize_newspapers contact_learningdisabilities reason_basketball bargain_cats support_software combine_foodbeverage canvass_newslive schedule_titanic1912 devote_basketball - tarea
        sandra_stewart norma_crawford kevin_garrett gerald_hicks fred_flores arthur_dean douglas_stanley nancy_gomez alan_bryant louis_perry mary_jackson thomas_brown beverly_simmons brandon_berry joe_burke daniel_richardson jeffrey_frazier arthur_howard doris_payne harold_morales carlos_hawkins shawn_weaver julia_hunt anthony_reynolds norma_rogers matthew_perry donna_russell carl_perkins mildred_taylor brandon_tucker judith_banks anne_sanders cynthia_reynolds karen_reed patrick_rogers juan_meyer brenda_campbell emily_andrews fred_stone philip_mendoza johnny_tucker kevin_cooper mark_graham ryan_ferguson keith_griffin jesse_turner ralph_porter - programador
    )
    (:init
        (= (dtarea reason_streetmaps) 2) (= (ttarea reason_streetmaps) 6) 
        (= (dtarea distribute_museums) 1) (= (ttarea distribute_museums) 9) 
        (= (dtarea produce_antitrustlaw) 1) (= (ttarea produce_antitrustlaw) 5) 
        (= (dtarea improvise_cancer) 3) (= (ttarea improvise_cancer) 3) 
        (= (dtarea instruct_arnoldfred) 2) (= (ttarea instruct_arnoldfred) 10) 
        (= (dtarea incorporate_moon) 3) (= (ttarea incorporate_moon) 9) 
        (= (dtarea compile_drugdictionary) 3) (= (ttarea compile_drugdictionary) 2) 
        (= (dtarea customize_localgovt) 2) (= (ttarea customize_localgovt) 8) 
        (= (dtarea propose_supremecourt) 1) (= (ttarea propose_supremecourt) 7) 
        (= (dtarea preside_travelinfo) 1) (= (ttarea preside_travelinfo) 2) 
        (= (dtarea share_investing) 2) (= (ttarea share_investing) 5) 
        (= (dtarea analyze_aviation) 1) (= (ttarea analyze_aviation) 1) 
        (= (dtarea collaborate_tvguide) 1) (= (ttarea collaborate_tvguide) 7) 
        (= (dtarea dedicate_localgovt) 2) (= (ttarea dedicate_localgovt) 10) 
        (= (dtarea commence_travelinfo) 3) (= (ttarea commence_travelinfo) 4) 
        (= (dtarea present_antiquestock) 1) (= (ttarea present_antiquestock) 10) 
        (= (dtarea win_gods) 2) (= (ttarea win_gods) 4) 
        (= (dtarea refer_politics) 2) (= (ttarea refer_politics) 4) 
        (= (dtarea inform_smokingsettlement) 3) (= (ttarea inform_smokingsettlement) 10) 
        (= (dtarea experiment_libraries) 2) (= (ttarea experiment_libraries) 8) 
        (= (dtarea boost_geography) 1) (= (ttarea boost_geography) 2) 
        (= (dtarea centralize_usstatesites) 2) (= (ttarea centralize_usstatesites) 3) 
        (= (dtarea enter_stockexchanges) 2) (= (ttarea enter_stockexchanges) 4) 
        (= (dtarea trace_stockcertificates) 1) (= (ttarea trace_stockcertificates) 1) 
        (= (dtarea rectify_stocksbonds) 2) (= (ttarea rectify_stocksbonds) 7) 
        (= (dtarea compare_greekgods) 2) (= (ttarea compare_greekgods) 6) 
        (= (dtarea extrapolate_people) 3) (= (ttarea extrapolate_people) 2) 
        (= (dtarea enlarge_dinosaurs) 1) (= (ttarea enlarge_dinosaurs) 7) 
        (= (dtarea attract_pregnancy) 1) (= (ttarea attract_pregnancy) 4) 
        (= (dtarea nurse_stockexchanges) 1) (= (ttarea nurse_stockexchanges) 8) 
        (= (dtarea foster_nosmoking) 1) (= (ttarea foster_nosmoking) 8) 
        (= (dtarea spoke_smokingsettlement) 3) (= (ttarea spoke_smokingsettlement) 3) 
        (= (dtarea conduct_corporatenews) 1) (= (ttarea conduct_corporatenews) 3) 
        (= (dtarea start_geometry) 3) (= (ttarea start_geometry) 9) 
        (= (dtarea enhance_geography) 1) (= (ttarea enhance_geography) 1) 
        (= (dtarea govern_drugeducation) 1) (= (ttarea govern_drugeducation) 10) 
        (= (dtarea transfer_spaceshuttle) 3) (= (ttarea transfer_spaceshuttle) 10) 
        (= (dtarea visualize_newspapers) 3) (= (ttarea visualize_newspapers) 2) 
        (= (dtarea contact_learningdisabilities) 3) (= (ttarea contact_learningdisabilities) 1) 
        (= (dtarea reason_basketball) 1) (= (ttarea reason_basketball) 3) 
        (= (dtarea bargain_cats) 2) (= (ttarea bargain_cats) 5) 
        (= (dtarea support_software) 3) (= (ttarea support_software) 7) 
        (= (dtarea combine_foodbeverage) 1) (= (ttarea combine_foodbeverage) 8) 
        (= (dtarea canvass_newslive) 3) (= (ttarea canvass_newslive) 10) 
        (= (dtarea schedule_titanic1912) 2) (= (ttarea schedule_titanic1912) 9) 
        (= (dtarea devote_basketball) 3) (= (ttarea devote_basketball) 8) 
        (= (hprog sandra_stewart) 1) (= (cprog sandra_stewart) 2) 
        (= (hprog norma_crawford) 2) (= (cprog norma_crawford) 2) 
        (= (hprog kevin_garrett) 3) (= (cprog kevin_garrett) 2) 
        (= (hprog gerald_hicks) 3) (= (cprog gerald_hicks) 2) 
        (= (hprog fred_flores) 2) (= (cprog fred_flores) 1) 
        (= (hprog arthur_dean) 2) (= (cprog arthur_dean) 1) 
        (= (hprog douglas_stanley) 1) (= (cprog douglas_stanley) 2) 
        (= (hprog nancy_gomez) 1) (= (cprog nancy_gomez) 2) 
        (= (hprog alan_bryant) 3) (= (cprog alan_bryant) 2) 
        (= (hprog louis_perry) 1) (= (cprog louis_perry) 2) 
        (= (hprog mary_jackson) 1) (= (cprog mary_jackson) 1) 
        (= (hprog thomas_brown) 2) (= (cprog thomas_brown) 1) 
        (= (hprog beverly_simmons) 2) (= (cprog beverly_simmons) 2) 
        (= (hprog brandon_berry) 2) (= (cprog brandon_berry) 2) 
        (= (hprog joe_burke) 1) (= (cprog joe_burke) 1) 
        (= (hprog daniel_richardson) 1) (= (cprog daniel_richardson) 1) 
        (= (hprog jeffrey_frazier) 1) (= (cprog jeffrey_frazier) 2) 
        (= (hprog arthur_howard) 2) (= (cprog arthur_howard) 1) 
        (= (hprog doris_payne) 2) (= (cprog doris_payne) 1) 
        (= (hprog harold_morales) 3) (= (cprog harold_morales) 2) 
        (= (hprog carlos_hawkins) 3) (= (cprog carlos_hawkins) 1) 
        (= (hprog shawn_weaver) 1) (= (cprog shawn_weaver) 2) 
        (= (hprog julia_hunt) 1) (= (cprog julia_hunt) 1) 
        (= (hprog anthony_reynolds) 2) (= (cprog anthony_reynolds) 1) 
        (= (hprog norma_rogers) 1) (= (cprog norma_rogers) 2) 
        (= (hprog matthew_perry) 3) (= (cprog matthew_perry) 2) 
        (= (hprog donna_russell) 3) (= (cprog donna_russell) 2) 
        (= (hprog carl_perkins) 2) (= (cprog carl_perkins) 1) 
        (= (hprog mildred_taylor) 2) (= (cprog mildred_taylor) 1) 
        (= (hprog brandon_tucker) 3) (= (cprog brandon_tucker) 2) 
        (= (hprog judith_banks) 2) (= (cprog judith_banks) 1) 
        (= (hprog anne_sanders) 1) (= (cprog anne_sanders) 2) 
        (= (hprog cynthia_reynolds) 3) (= (cprog cynthia_reynolds) 2) 
        (= (hprog karen_reed) 1) (= (cprog karen_reed) 1) 
        (= (hprog patrick_rogers) 1) (= (cprog patrick_rogers) 1) 
        (= (hprog juan_meyer) 3) (= (cprog juan_meyer) 1) 
        (= (hprog brenda_campbell) 2) (= (cprog brenda_campbell) 2) 
        (= (hprog emily_andrews) 3) (= (cprog emily_andrews) 1) 
        (= (hprog fred_stone) 1) (= (cprog fred_stone) 2) 
        (= (hprog philip_mendoza) 2) (= (cprog philip_mendoza) 1) 
        (= (hprog johnny_tucker) 3) (= (cprog johnny_tucker) 1) 
        (= (hprog kevin_cooper) 2) (= (cprog kevin_cooper) 1) 
        (= (hprog mark_graham) 1) (= (cprog mark_graham) 2) 
        (= (hprog ryan_ferguson) 3) (= (cprog ryan_ferguson) 1) 
        (= (hprog keith_griffin) 3) (= (cprog keith_griffin) 1) 
        (= (hprog jesse_turner) 1) (= (cprog jesse_turner) 2) 
        (= (hprog ralph_porter) 2) (= (cprog ralph_porter) 2) 
        (= (ttotal) 0) 
    )
    (:goal
        (forall (?t - tarea) (revisada ?t))
    )
    (:metric minimize
        (ttotal)
    )
)