(define (problem problema)
    (:domain tareas-ext2)
    (:objects 
        enable_entertainment assess_travelmaps demonstrate_foodbeverage apply_marinelife arbitrate_johnwayne fabricate_johnwayne influence_mathematics rectify_dinosaurs supervise_leopards practice_electricity recall_basketball related_finance earn_liveradio accumulate_oceanography inspect_health explore_sun acquire_spaceplanets extract_arnoldfred show_kangaroo adjust_moon conduct_ciafacts debate_comets transmit_hubblespacetelescope lobby_maillists use_streetmaps produce_legallaw - tarea
        paul_burke carolyn_martin kevin_garrett kathryn_dunn victor_greene kathleen_holmes shawn_davis charles_barnes karen_reed jonathan_riley kevin_matthews timothy_knight adam_kim shawn_weaver dorothy_lynch sara_adams margaret_martin shirley_smith steve_nichols ryan_garrett susan_harvey samuel_daniels robin_nichols mary_burton jeffrey_bowman jacqueline_gutierrez peter_stanley nicholas_harper christine_bishop carlos_wilson mildred_chavez heather_spencer thomas_brown harold_cruz gary_alvarez james_meyer louis_sanchez margaret_gibson gregory_morris matthew_pierce clarence_holmes wayne_ferguson jesse_holmes nancy_sanchez kelly_richards jason_hanson angela_thomas harold_taylor jean_sanchez jack_foster arthur_gonzales brenda_jordan harold_morales beverly_edwards louise_gonzalez patrick_dixon lillian_evans kathleen_gonzales joe_burke ruth_gardner nicole_bradley rachel_burke charles_murray fred_stone elizabeth_frazier julie_rogers roger_andrews lisa_mason ryan_gardner robert_holmes chris_perez jeremy_gray angela_burton clarence_collins gloria_cole julie_wright teresa_boyd - programador
    )
    (:init
        (= (dtarea enable_entertainment) 3) (= (ttarea enable_entertainment) 3) 
        (= (dtarea assess_travelmaps) 3) (= (ttarea assess_travelmaps) 2) 
        (= (dtarea demonstrate_foodbeverage) 1) (= (ttarea demonstrate_foodbeverage) 8) 
        (= (dtarea apply_marinelife) 1) (= (ttarea apply_marinelife) 4) 
        (= (dtarea arbitrate_johnwayne) 2) (= (ttarea arbitrate_johnwayne) 6) 
        (= (dtarea fabricate_johnwayne) 1) (= (ttarea fabricate_johnwayne) 5) 
        (= (dtarea influence_mathematics) 3) (= (ttarea influence_mathematics) 8) 
        (= (dtarea rectify_dinosaurs) 3) (= (ttarea rectify_dinosaurs) 1) 
        (= (dtarea supervise_leopards) 3) (= (ttarea supervise_leopards) 2) 
        (= (dtarea practice_electricity) 2) (= (ttarea practice_electricity) 8) 
        (= (dtarea recall_basketball) 3) (= (ttarea recall_basketball) 8) 
        (= (dtarea related_finance) 2) (= (ttarea related_finance) 9) 
        (= (dtarea earn_liveradio) 1) (= (ttarea earn_liveradio) 7) 
        (= (dtarea accumulate_oceanography) 2) (= (ttarea accumulate_oceanography) 6) 
        (= (dtarea inspect_health) 3) (= (ttarea inspect_health) 8) 
        (= (dtarea explore_sun) 2) (= (ttarea explore_sun) 10) 
        (= (dtarea acquire_spaceplanets) 2) (= (ttarea acquire_spaceplanets) 3) 
        (= (dtarea extract_arnoldfred) 1) (= (ttarea extract_arnoldfred) 8) 
        (= (dtarea show_kangaroo) 3) (= (ttarea show_kangaroo) 9) 
        (= (dtarea adjust_moon) 3) (= (ttarea adjust_moon) 7) 
        (= (dtarea conduct_ciafacts) 2) (= (ttarea conduct_ciafacts) 10) 
        (= (dtarea debate_comets) 1) (= (ttarea debate_comets) 5) 
        (= (dtarea transmit_hubblespacetelescope) 2) (= (ttarea transmit_hubblespacetelescope) 6) 
        (= (dtarea lobby_maillists) 2) (= (ttarea lobby_maillists) 10) 
        (= (dtarea use_streetmaps) 1) (= (ttarea use_streetmaps) 6) 
        (= (dtarea produce_legallaw) 3) (= (ttarea produce_legallaw) 8) 
        (= (hprog paul_burke) 2) (= (cprog paul_burke) 2) 
        (= (hprog carolyn_martin) 1) (= (cprog carolyn_martin) 1) 
        (= (hprog kevin_garrett) 1) (= (cprog kevin_garrett) 1) 
        (= (hprog kathryn_dunn) 2) (= (cprog kathryn_dunn) 2) 
        (= (hprog victor_greene) 2) (= (cprog victor_greene) 2) 
        (= (hprog kathleen_holmes) 3) (= (cprog kathleen_holmes) 2) 
        (= (hprog shawn_davis) 1) (= (cprog shawn_davis) 2) 
        (= (hprog charles_barnes) 1) (= (cprog charles_barnes) 1) 
        (= (hprog karen_reed) 3) (= (cprog karen_reed) 1) 
        (= (hprog jonathan_riley) 3) (= (cprog jonathan_riley) 2) 
        (= (hprog kevin_matthews) 1) (= (cprog kevin_matthews) 2) 
        (= (hprog timothy_knight) 2) (= (cprog timothy_knight) 2) 
        (= (hprog adam_kim) 3) (= (cprog adam_kim) 2) 
        (= (hprog shawn_weaver) 3) (= (cprog shawn_weaver) 2) 
        (= (hprog dorothy_lynch) 3) (= (cprog dorothy_lynch) 1) 
        (= (hprog sara_adams) 1) (= (cprog sara_adams) 1) 
        (= (hprog margaret_martin) 1) (= (cprog margaret_martin) 1) 
        (= (hprog shirley_smith) 2) (= (cprog shirley_smith) 2) 
        (= (hprog steve_nichols) 3) (= (cprog steve_nichols) 1) 
        (= (hprog ryan_garrett) 1) (= (cprog ryan_garrett) 2) 
        (= (hprog susan_harvey) 2) (= (cprog susan_harvey) 2) 
        (= (hprog samuel_daniels) 2) (= (cprog samuel_daniels) 2) 
        (= (hprog robin_nichols) 1) (= (cprog robin_nichols) 1) 
        (= (hprog mary_burton) 3) (= (cprog mary_burton) 2) 
        (= (hprog jeffrey_bowman) 1) (= (cprog jeffrey_bowman) 2) 
        (= (hprog jacqueline_gutierrez) 3) (= (cprog jacqueline_gutierrez) 1) 
        (= (hprog peter_stanley) 1) (= (cprog peter_stanley) 1) 
        (= (hprog nicholas_harper) 3) (= (cprog nicholas_harper) 1) 
        (= (hprog christine_bishop) 1) (= (cprog christine_bishop) 2) 
        (= (hprog carlos_wilson) 1) (= (cprog carlos_wilson) 2) 
        (= (hprog mildred_chavez) 1) (= (cprog mildred_chavez) 1) 
        (= (hprog heather_spencer) 2) (= (cprog heather_spencer) 1) 
        (= (hprog thomas_brown) 2) (= (cprog thomas_brown) 1) 
        (= (hprog harold_cruz) 2) (= (cprog harold_cruz) 1) 
        (= (hprog gary_alvarez) 3) (= (cprog gary_alvarez) 1) 
        (= (hprog james_meyer) 1) (= (cprog james_meyer) 2) 
        (= (hprog louis_sanchez) 3) (= (cprog louis_sanchez) 2) 
        (= (hprog margaret_gibson) 2) (= (cprog margaret_gibson) 2) 
        (= (hprog gregory_morris) 1) (= (cprog gregory_morris) 2) 
        (= (hprog matthew_pierce) 1) (= (cprog matthew_pierce) 2) 
        (= (hprog clarence_holmes) 1) (= (cprog clarence_holmes) 2) 
        (= (hprog wayne_ferguson) 2) (= (cprog wayne_ferguson) 2) 
        (= (hprog jesse_holmes) 2) (= (cprog jesse_holmes) 1) 
        (= (hprog nancy_sanchez) 1) (= (cprog nancy_sanchez) 2) 
        (= (hprog kelly_richards) 2) (= (cprog kelly_richards) 2) 
        (= (hprog jason_hanson) 1) (= (cprog jason_hanson) 2) 
        (= (hprog angela_thomas) 1) (= (cprog angela_thomas) 1) 
        (= (hprog harold_taylor) 3) (= (cprog harold_taylor) 1) 
        (= (hprog jean_sanchez) 3) (= (cprog jean_sanchez) 2) 
        (= (hprog jack_foster) 2) (= (cprog jack_foster) 2) 
        (= (hprog arthur_gonzales) 1) (= (cprog arthur_gonzales) 1) 
        (= (hprog brenda_jordan) 1) (= (cprog brenda_jordan) 2) 
        (= (hprog harold_morales) 1) (= (cprog harold_morales) 1) 
        (= (hprog beverly_edwards) 1) (= (cprog beverly_edwards) 2) 
        (= (hprog louise_gonzalez) 3) (= (cprog louise_gonzalez) 2) 
        (= (hprog patrick_dixon) 3) (= (cprog patrick_dixon) 1) 
        (= (hprog lillian_evans) 3) (= (cprog lillian_evans) 2) 
        (= (hprog kathleen_gonzales) 2) (= (cprog kathleen_gonzales) 2) 
        (= (hprog joe_burke) 3) (= (cprog joe_burke) 1) 
        (= (hprog ruth_gardner) 2) (= (cprog ruth_gardner) 2) 
        (= (hprog nicole_bradley) 2) (= (cprog nicole_bradley) 1) 
        (= (hprog rachel_burke) 3) (= (cprog rachel_burke) 1) 
        (= (hprog charles_murray) 1) (= (cprog charles_murray) 1) 
        (= (hprog fred_stone) 3) (= (cprog fred_stone) 1) 
        (= (hprog elizabeth_frazier) 2) (= (cprog elizabeth_frazier) 2) 
        (= (hprog julie_rogers) 1) (= (cprog julie_rogers) 2) 
        (= (hprog roger_andrews) 2) (= (cprog roger_andrews) 1) 
        (= (hprog lisa_mason) 2) (= (cprog lisa_mason) 2) 
        (= (hprog ryan_gardner) 1) (= (cprog ryan_gardner) 1) 
        (= (hprog robert_holmes) 1) (= (cprog robert_holmes) 2) 
        (= (hprog chris_perez) 2) (= (cprog chris_perez) 2) 
        (= (hprog jeremy_gray) 1) (= (cprog jeremy_gray) 1) 
        (= (hprog angela_burton) 3) (= (cprog angela_burton) 2) 
        (= (hprog clarence_collins) 1) (= (cprog clarence_collins) 2) 
        (= (hprog gloria_cole) 2) (= (cprog gloria_cole) 1) 
        (= (hprog julie_wright) 2) (= (cprog julie_wright) 1) 
        (= (hprog teresa_boyd) 3) (= (cprog teresa_boyd) 2) 
        (= (ttotal) 0) 
    )
    (:goal
        (forall (?t - tarea) (revisada ?t))
    )
    (:metric minimize
        (ttotal)
    )
)