(define (problem problema)
    (:domain tareas-ext1)
    (:objects 
        enumerate_supremecourt update_dogs order_internetwebsite augment_solarsystem tail_gorillas teach_epilepsy restore_movies familiarize_bigbrothercams complete_nosmoking participate_beveragecompanies plan_geometry compare_communicationsindustryhistory filter_censusbureau - tarea
        keith_griffin marie_wagner deborah_henry adam_martinez andrew_fox harry_stone david_perez alice_carroll carlos_kelley phillip_hart jeffrey_bowman brian_kim jennifer_watson peter_reyes stephen_collins evelyn_alexander teresa_smith evelyn_myers nicholas_gordon susan_ward tina_white jerry_gordon melissa_johnson terry_cunningham timothy_weaver pamela_gibson - programador
    )
    (:init
        (= (dtarea enumerate_supremecourt) 3) (= (ttarea enumerate_supremecourt) 7) 
        (= (dtarea update_dogs) 1) (= (ttarea update_dogs) 5) 
        (= (dtarea order_internetwebsite) 1) (= (ttarea order_internetwebsite) 7) 
        (= (dtarea augment_solarsystem) 2) (= (ttarea augment_solarsystem) 9) 
        (= (dtarea tail_gorillas) 2) (= (ttarea tail_gorillas) 8) 
        (= (dtarea teach_epilepsy) 3) (= (ttarea teach_epilepsy) 8) 
        (= (dtarea restore_movies) 3) (= (ttarea restore_movies) 4) 
        (= (dtarea familiarize_bigbrothercams) 3) (= (ttarea familiarize_bigbrothercams) 8) 
        (= (dtarea complete_nosmoking) 3) (= (ttarea complete_nosmoking) 2) 
        (= (dtarea participate_beveragecompanies) 1) (= (ttarea participate_beveragecompanies) 8) 
        (= (dtarea plan_geometry) 3) (= (ttarea plan_geometry) 6) 
        (= (dtarea compare_communicationsindustryhistory) 1) (= (ttarea compare_communicationsindustryhistory) 6) 
        (= (dtarea filter_censusbureau) 3) (= (ttarea filter_censusbureau) 10) 
        (= (hprog keith_griffin) 1) (= (cprog keith_griffin) 1) 
        (= (hprog marie_wagner) 2) (= (cprog marie_wagner) 2) 
        (= (hprog deborah_henry) 2) (= (cprog deborah_henry) 2) 
        (= (hprog adam_martinez) 3) (= (cprog adam_martinez) 1) 
        (= (hprog andrew_fox) 3) (= (cprog andrew_fox) 2) 
        (= (hprog harry_stone) 1) (= (cprog harry_stone) 1) 
        (= (hprog david_perez) 1) (= (cprog david_perez) 2) 
        (= (hprog alice_carroll) 2) (= (cprog alice_carroll) 2) 
        (= (hprog carlos_kelley) 3) (= (cprog carlos_kelley) 1) 
        (= (hprog phillip_hart) 3) (= (cprog phillip_hart) 1) 
        (= (hprog jeffrey_bowman) 1) (= (cprog jeffrey_bowman) 1) 
        (= (hprog brian_kim) 1) (= (cprog brian_kim) 1) 
        (= (hprog jennifer_watson) 2) (= (cprog jennifer_watson) 2) 
        (= (hprog peter_reyes) 3) (= (cprog peter_reyes) 2) 
        (= (hprog stephen_collins) 3) (= (cprog stephen_collins) 1) 
        (= (hprog evelyn_alexander) 1) (= (cprog evelyn_alexander) 2) 
        (= (hprog teresa_smith) 3) (= (cprog teresa_smith) 2) 
        (= (hprog evelyn_myers) 2) (= (cprog evelyn_myers) 2) 
        (= (hprog nicholas_gordon) 1) (= (cprog nicholas_gordon) 2) 
        (= (hprog susan_ward) 1) (= (cprog susan_ward) 2) 
        (= (hprog tina_white) 2) (= (cprog tina_white) 2) 
        (= (hprog jerry_gordon) 2) (= (cprog jerry_gordon) 2) 
        (= (hprog melissa_johnson) 1) (= (cprog melissa_johnson) 2) 
        (= (hprog terry_cunningham) 2) (= (cprog terry_cunningham) 2) 
        (= (hprog timothy_weaver) 1) (= (cprog timothy_weaver) 2) 
        (= (hprog pamela_gibson) 1) (= (cprog pamela_gibson) 1) 
    )
    (:goal
        (forall (?t - tarea) (revisada ?t))
    )
)